### ISSUE TITLE
Red Hat uses this by default, so how can it be deprecated?

### ISSUE THREAD

**Issue by rafrafek** [nodeshift-archived/centos7-s2i-nodejs#205]
Red Hat uses this by default when Node.js is selected, so how can it be deprecated?

https://developers.redhat.com/launch/flow/import-existing-app

**Comment by lholmquist** [comment]
I went to the link,  but not sure what i'm suppose to click on next.  could you take a screenshot of the thing you are looking at?

**Comment by rafrafek** [comment]
Go to link -> Click "Select Import" button -> Paste link to any Node.js app source, e.g. `https://github.com/heroku/node-js-getting-started` -> You can see that **Generic Node.js Code Builder(nodeshift/centos7-s2i-nodejs)** is automatically selected.

**Comment by lholmquist** [comment]
@rafrafek thanks.  This was obviously missed during our migration to UBI8

**Comment by quintesse** [comment]
This has now been removed from the Launcher.

Btw, the Launcher is *not* a Red Hat supported product so might receive updates late (if ever).

**Comment by quintesse** [comment]
(This can probably be closed now)

**Comment by lholmquist** [comment]
Thanks for updating that @quintesse
